version: '3.8'

services:
  blog-app: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:5000"
    env_file:
      - .env
    networks:
      - blog-network
    depends_on:
      - db
    restart: always
    
  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432" #external:internal
    env_file:
      - .env
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge    